services:
  web:
    build: .
    restart: always
    ports:
      - 127.0.0.1:5001:5000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - EMAIL_DOMAIN
      - SECRET_KEY
    depends_on:
      - db
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
