"""Add boolean visible to Lesson

Revision ID: 85ef9c63ef6c
Revises: 8c814249e161
Create Date: 2025-05-20 12:08:22.292457

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "85ef9c63ef6c"
down_revision = "8c814249e161"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lesson", schema=None) as batch_op:
        batch_op.add_column(sa.Column("visible", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lesson", schema=None) as batch_op:
        batch_op.drop_column("visible")

    # ### end Alembic commands ###
